version: '3.8'

services:
  milyoner-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://milyoner-backend-216260080307.europe-west3.run.app}
    container_name: frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - milyoner-network

networks:
  milyoner-network:
    name: milyoner-shared-network
    external: true